### ISSUE TITLE
Merge included array in request body with relationships

### ISSUE THREAD

**Issue by nilsding** [runtastic/request_handler#10]
The `BodyParser` class currently [flattens][flattens] the `attributes` and `relationships` objects from the request body.  It does however not merge the relationship attributes from the request body's `included` array.  This would make describing the schema of new relationships easier when the request includes the attributes of the relationship inside the `included` array.

Note that the official JSON API specification only includes the `included` array in the response, and not the request itself.  In fact, the JSON API specs do not consider the creation of new relationships while creating a new resource at all, as it is expected that the associated objects already exist.

@andreaseger @raphaelhetzel What are your thoughts on that? 

[flattens]: https://github.com/runtastic/request_handler/blob/v0.9.1/lib/request_handler/body_parser.rb#L18

**Comment by andreaseger** [comment]
first we definitely have to motivate our decision to support included relationship entities in bodies and make this optional (i.e. we only want to allow this on create bodies but not on update bodies)

second could you propose how the structure looks after we merged the included relationship entities into the main body? Ideally with a before (i.e. jsonapi structure) and after (i.e. ruby hash). Please also consider how this would work if one of the included entities is referenced multiple times as a relationship.

**Comment by nilsding** [comment]
Making this optional shouldn't be a big problem since it could be easily set on demand, e.g. in the `options do ... end` block.

This is what I had in mind: (taking the example object from jsonapi.org without links as an example)

Before:

<details> 
  <summary><strong>Example JSON API object</strong> (click to expand)</summary>

``` json
{
    "data": {
        "type": "articles",
        "id": "1",
        "attributes": {
            "title": "JSON API paints my bikeshed!"
        },
        "relationships": {
            "author": {
                "data": {
                    "type": "people",
                    "id": "9"
                }
            },
            "comments": {
                "data": [
                    {
                        "type": "comments",
                        "id": "5"
                    },
                    {
                        "type": "comments",
                        "id": "12"
                    }
                ]
            }
        }
    },
    "included": [
        {
            "type": "people",
            "id": "9",
            "attributes": {
                "first-name": "Dan",
                "last-name": "Gebhardt",
                "twitter": "dgeb"
            }
        },
        {
            "type": "comments",
            "id": "5",
            "attributes": {
                "body": "First!"
            },
            "relationships": {
                "author": {
                    "data": {
                        "type": "people",
                        "id": "2"
                    }
                }
            }
        },
        {
            "type": "comments",
            "id": "12",
            "attributes": {
                "body": "I like XML better"
            },
            "relationships": {
                "author": {
                    "data": {
                        "type": "people",
                        "id": "9"
                    }
                }
            }
        }
    ]
}
```

</details>
<p>

after:

<details> 
  <summary><strong>Ruby hash structure</strong> (click to expand)</summary>

``` ruby
{
        "type" => "articles",
          "id" => "1",
       "title" => "JSON API paints my bikeshed!",
      "author" => {
             "type" => "people",
               "id" => "9",
        "last-name" => "Gebhardt",
          "twitter" => "dgeb"
    },
    "comments" => [
        {
              "type" => "comments",
                "id" => "5",
              "body" => "First!",
            "author" => {
                "type" => "people",
                  "id" => "2"
            }
        },
        {
              "type" => "comments",
                "id" => "12",
              "body" => "I like XML better",
            "author" => {
                "type" => "people",
                  "id" => "9"
                # note that the attributes of the relationships are not included again
            }
        }
    ]
}
```

</details>

**Comment by andreaseger** [comment]
What do you thing about a structure like this:

```ruby
[
  {
    type: "articles",
    id: "1",
    title: "JSON API paints my bikeshed!",
    author: {
      type: "people",
      id: "9"
    },
    comments: [
      {
        "type": "comments",
       "id": "5"
      },
      {
        "type": "comments",
       "id": "12"
      }
    ]
  },
  {
    type: "people",
    id: "9"
    "last-name" => "Gebhardt",
    twitter: "dgeb"
  },
  {
    type: "comments",
    id: "5",
    body: "First!",
    author: {
      type: "people",
      id: "2"
    }
  },
  {
    type: "comments",
    id: "12",
    body: "I like XML better",
    author: {
      type: "people",
      id: "9"
    }
  }
]
```

**Comment by raphaelhetzel** [comment]
The only problem i see with that is that you have to .select the parent element out of the elements with that structure.

**Comment by andreaseger** [comment]
On the other hand the main resource looks exactly the same as if the relationships where already present.

In the nested structure you'd have to traverse the nested structure to find secondary resources to create

**Comment by nilsding** [comment]
True, but the nested structure makes schema validation a bit easier (at least considering how it is defined right now: only for a single type)

Thinking about schema definition, I think with your structure it would be good to define a schema for each type that can be included, e.g. like this:

``` ruby
options do
  body do
    schema(Dry::Validation.JSON do
             # ... articles schema ...
           end)
    included do
      schema(:people, Dry::Validation.JSON do
                        # ... people schema ...
                      end)
      schema(:comments, Dry::Validation.JSON do
                          # ... comments schema ...
                        end)
    end
  end
end
```

**Comment by nilsding** [comment]
since #13 was merged I'll consider this as done
