### ISSUE TITLE
Proposition: seperate filters and url parameters

### ISSUE THREAD

**Issue by Goltergaul** [runtastic/request_handler#12]
Currently you can use the `additional_url_filter` method to merge url_parameters into the filters and validate them using the filter schema.

Imo this is problematic because then you have filters and non-filters mixed into the same thing. For example if you use the filters to build a pagination url you don't know which ones where the real filters anymore. It would be better to have the url params in a seperate object that is returned from the request handler. This would entail to be able to define a seperate validation schema for url parameters as well, which would be fine imo.

**Comment by andreaseger** [comment]
hmm I don't really see a problem with having them returned in one structure. I say That is even an advantage later on as all filters are combined and use_cases don't have to combine multiple structs later.

As for pagination links you need to know how your url looks anyway so you need to know at that point which parameters need to go into the url and which into the query parameters.

Example:
given a uri like

`/v1/users/123/photos?filter[type]=thumbnail`

in your data access layer you need to have both the user_id and the type so having a struct like `{user_id: 123, type: "thumbnail"}` makes sense and is more straight forward to use.

When building pagination links you probably have a url template like `/v1/users/#{user_id}/photos` and have the knowledge that you will need the user_id from the filters. In essence you can do simply the following:

```ruby
user_id = filter.delete(:user_id)
url = "/v1/users/#{user_id}/photos?#{hash_to_query_param_filter_string(filter)}"
```

given that `Hash#delete` mutates the hash in line 2 you're left with all other filters to go into the query parameter.

Or am I missing something here?

**Comment by raphaelhetzel** [comment]
I would personally do something like that with the delete way @andreaseger already mentioned, or use a list of filters that are actually wanted as query parameters in the url builder, but if you really want a separate list for each you can also generate it in your handler like this:

```ruby
def to_dto
  Openstruct.new(
  url_params: filter_params.select { |key, _value| config.filter.additional_url_filter.include?(key) }
  query_params: filter_params.reject { |key, _value| config.filter.additional_url_filter.include?(key) }
  )
end

**Comment by Goltergaul** [comment]
@andreaseger yes and no... if the link building is very abstract than it does not know what goes where it just takes all the filters and puts them into the query params and reuses the current url as is.

@raphaelhetzel this seems like a good workaround

**Comment by andreaseger** [comment]
I'll close this issue for now
