### ISSUE TITLE
[Suggestion] Hide use of dry-validation behind private interface

### ISSUE THREAD

**Issue by AMHOL** [runtastic/request_handler#26]
Hi, I was discussing your project with @ahmgeek on Gitter and I suggested that you should hide the dry-* libraries behind your own interfaces, the suggestion for dry-validation was:

Rather than:

```ruby
query do
  schema(
    Dry::Validation.Form do
      optional(:name).filled(:str?)
    end
  )
end
```

Something like...

```ruby
query do
  schema(:form) do
    optional(:name).filled(:str?)
  end
end
```

**Comment by andreaseger** [comment]
yeah this would be nice especially given the issue around ruby parsing blocks wrong if you forget the parenthesis. But it would right now also mean changing some internal re. how the options-tree is build. Currently this is simply a confstruct and we select certain paths / walk through the tree.

But I will keep this in mind and an improvement.

**Comment by alexJunger** [comment]
What would be the motivation to build a DSL on top of dry-validation?

**Comment by andreaseger** [comment]
This suggestion is from ~1.5 years ago. It would allow for a bit nicer DSL of the request_handler itself and maybe fix some annoyances around the use of confstruct for the nested dsl.
But now with the "pluggable" validation engines this is no longer relevant
