### ISSUE TITLE
add clear error handling for accessing not configured params

### ISSUE THREAD

**Issue by andreaseger** [runtastic/request_handler#4]
Right now it is not cleanly handled if someone wants to access e.g. `fieldsets_params` without defining the fieldsets options correctly. Same with other params.

We have to decide on how to handle this, some options could be
1. return an empty set/hash/datastructure
2. raise `NoConfigAvailableError`
3. raise some other error

**Comment by raphaelhetzel** [comment]
https://github.com/runtastic/request_handler/pull/5
