### ISSUE TITLE
NoMethodError when accessing params with symbols as keys

### ISSUE THREAD

**Issue by nilsding** [runtastic/request_handler#6]
I just noticed that a `NoMethodError` is occurring when accessing the `params` hash which contains one or more keys that are symbols.

The error occurs in the block in [RequestHandler::Base#params](https://github.com/runtastic/request_handler/blob/v0.9.1/lib/request_handler/base.rb#L128) which replaces every dot with the separator.  

Here is an example script that describes this bug:

``` ruby
require 'bundler/inline'
require 'yaml'

gemfile true do
  source 'https://rubygems.org'
  gem 'request_handler', '0.9.1'
  gem 'sinatra', '~> 1.4.8'
end

class MyHandler < RequestHandler::Base
  def to_dto
    "<pre>... DTO goes here ...\n\nparams are:\n#{params.to_yaml}"
  end
end

class MySinatraApp < Sinatra::Base
  get '/' do
    # This will blow up:
    params[:symbol_key] = 'test'
    # This will not:
    params['string_key'] = 'test'

    request.params.merge!(params)
    MyHandler.new(request: request).to_dto
  end
end

Rack::Server.start(app: MySinatraApp.new)
```

**Comment by raphaelhetzel** [comment]
The actual request params are always strings, thats why it did not come up so far, as you usually don't set any params yourself. 
Casting all request keys in the base class would solve that.

**Comment by andreaseger** [comment]
input params should always have string keys - that's why we currently made that assumption.

But I'm happy to accept a PR to support your usecase (e.g. by casting all keys to string before transforming them)
