### ISSUE TITLE
Disable RuboCop BlockLength cop for the handler options

### ISSUE THREAD

**Issue by raphaelhetzel** [runtastic/request_handler#7]
As nearly every bigger request handler will trigger the BlockLength cop with options block,
we should disable it for the options block in all handlers. However i'm unsure how to handle this as the comment method does not work with class extension and editing thy rubycop.yml also is not ideal.

**Comment by andreaseger** [comment]
this is not in scope of this gem itself. A dev has to consider this them self for the application this gem is used.
